# Generated by Django 5.2.2 on 2025-09-29 04:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الهدف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('goal_type', models.CharField(choices=[('savings', 'ادخار'), ('debt_payment', 'سداد دين'), ('investment', 'استثمار'), ('major_purchase', 'شراء كبير'), ('emergency_fund', 'صندوق الطوارئ'), ('education', 'تعليم'), ('retirement', 'تقاعد'), ('travel', 'سفر'), ('wedding', 'زفاف'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الهدف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المستهدف')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ الحالي')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('target_date', models.DateField(verbose_name='التاريخ المستهدف')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('paused', 'متوقف'), ('cancelled', 'ملغي')], default='active', max_length=10, verbose_name='الحالة')),
                ('monthly_target', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='الهدف الشهري')),
                ('color', models.CharField(default='#ffc107', max_length=7, verbose_name='لون الهدف')),
                ('icon', models.CharField(default='fas fa-target', max_length=100, verbose_name='أيقونة الهدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المرتبط')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='التصنيف المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'هدف مالي',
                'verbose_name_plural': 'الأهداف المالية',
                'ordering': ['priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('contribution_type', models.CharField(choices=[('manual', 'يدوي'), ('automatic', 'تلقائي'), ('transaction', 'من معاملة'), ('transfer', 'تحويل')], default='manual', max_length=15, verbose_name='نوع المساهمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المساهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب المصدر')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.financialgoal', verbose_name='الهدف')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction', verbose_name='المعاملة المرتبطة')),
            ],
            options={
                'verbose_name': 'مساهمة في هدف',
                'verbose_name_plural': 'مساهمات الأهداف',
                'ordering': ['-contribution_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعلم')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ المستهدف للمعلم')),
                ('target_date', models.DateField(verbose_name='التاريخ المستهدف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='محقق')),
                ('achieved_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('reward_description', models.TextField(blank=True, null=True, verbose_name='وصف المكافأة')),
                ('color', models.CharField(default='#6f42c1', max_length=7, verbose_name='لون المعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.financialgoal', verbose_name='المعالم')),
            ],
            options={
                'verbose_name': 'معلم هدف',
                'verbose_name_plural': 'معالم الأهداف',
                'ordering': ['target_amount', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('goal_type', models.CharField(choices=[('savings', 'ادخار'), ('debt_payment', 'سداد دين'), ('investment', 'استثمار'), ('major_purchase', 'شراء كبير'), ('emergency_fund', 'صندوق الطوارئ'), ('education', 'تعليم'), ('retirement', 'تقاعد'), ('travel', 'سفر'), ('wedding', 'زفاف'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الهدف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('default_duration_months', models.PositiveIntegerField(default=12, verbose_name='المدة الافتراضية بالأشهر')),
                ('color', models.CharField(default='#ffc107', max_length=7, verbose_name='اللون')),
                ('icon', models.CharField(default='fas fa-target', max_length=100, verbose_name='الأيقونة')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب هدف',
                'verbose_name_plural': 'قوالب الأهداف',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
