# Generated by Django 5.2.2 on 2025-09-29 04:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العملة')),
                ('symbol', models.CharField(max_length=10, verbose_name='رمز العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=18, verbose_name='سعر الصرف')),
                ('is_primary', models.BooleanField(default=False, verbose_name='عملة أساسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('savings', 'حساب توفير'), ('current', 'حساب جاري'), ('credit', 'حساب ائتمان'), ('cash', 'نقد'), ('investment', 'استثمار'), ('debt', 'دين'), ('other', 'أخرى')], default='current', max_length=20, verbose_name='نوع الحساب')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الرصيد الابتدائي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الرصيد الحالي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='لون الحساب')),
                ('icon', models.CharField(default='fas fa-wallet', max_length=100, verbose_name='أيقونة الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=18, verbose_name='سعر الصرف')),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ المحول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.account', verbose_name='من حساب')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.account', verbose_name='إلى حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحويل بين الحسابات',
                'verbose_name_plural': 'التحويلات بين الحسابات',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('account_type', models.CharField(choices=[('savings', 'حساب توفير'), ('current', 'حساب جاري'), ('credit', 'حساب ائتمان'), ('cash', 'نقد'), ('investment', 'استثمار'), ('debt', 'دين'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='لون الحساب')),
                ('icon', models.CharField(default='fas fa-wallet', max_length=100, verbose_name='أيقونة الحساب')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currency', verbose_name='العملة الافتراضية')),
            ],
            options={
                'verbose_name': 'قالب حساب',
                'verbose_name_plural': 'قوالب الحسابات',
                'ordering': ['name'],
            },
        ),
    ]
