# Generated by Django 5.2.2 on 2025-09-29 04:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم العلامة')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='لون العلامة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
            ],
            options={
                'verbose_name': 'علامة معاملة',
                'verbose_name_plural': 'علامات المعاملات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('income', 'دخل'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=10, verbose_name='نوع المعاملة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='completed', max_length=10, verbose_name='الحالة')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='معاملة متكررة')),
                ('recurrence_type', models.CharField(choices=[('none', 'للمرة الواحدة'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('custom', 'مخصص')], default='none', max_length=10, verbose_name='نوع التكرار')),
                ('recurrence_interval', models.PositiveIntegerField(default=1, verbose_name='فترة التكرار')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='الرصيد بعد المعاملة')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('effective_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ الفعلي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('tags', models.ManyToManyField(blank=True, to='transactions.transactiontag', verbose_name='العلامات')),
            ],
            options={
                'verbose_name': 'معاملة',
                'verbose_name_plural': 'المعاملات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transaction_attachments/%Y/%m/%d/', verbose_name='الملف')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_attachments', to='transactions.transaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'مرفق معاملة',
                'verbose_name_plural': 'مرفقات المعاملات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='transactions.transaction', verbose_name='المعاملة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('income', 'دخل'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=10, verbose_name='نوع المعاملة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='التصنيف')),
                ('tags', models.ManyToManyField(blank=True, to='transactions.transactiontag', verbose_name='العلامات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قالب معاملة',
                'verbose_name_plural': 'قوالب المعاملات',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_98a6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='transaction_account_4f6194_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='transaction_categor_720c85_idx'),
        ),
    ]
