# Generated by Django 5.2.2 on 2025-09-29 04:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('report_type', models.CharField(choices=[('income_statement', 'بيان الدخل'), ('balance_sheet', 'الميزانية العمومية'), ('cash_flow', 'تدفق النقد'), ('budget_variance', 'تباين الميزانية'), ('category_summary', 'ملخص التصنيفات'), ('monthly_summary', 'ملخص شهري'), ('yearly_summary', 'ملخص سنوي'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('chart_types', models.JSONField(default=list, verbose_name='أنواع الرسوم البيانية')),
                ('date_range_days', models.PositiveIntegerField(default=30, verbose_name='نطاق التاريخ بالأيام')),
                ('include_categories', models.JSONField(default=list, verbose_name='التصنيفات المضمنة')),
                ('include_accounts', models.JSONField(default=list, verbose_name='الحسابات المضمنة')),
                ('default_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='html', max_length=10, verbose_name='التنسيق الافتراضي')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربعي'), ('yearly', 'سنوي')], max_length=15, verbose_name='التكرار')),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='يوم الأسبوع')),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='يوم الشهر')),
                ('output_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='تنسيق المخرجات')),
                ('email_recipients', models.JSONField(default=list, verbose_name='متلقو البريد الإلكتروني')),
                ('save_to_files', models.BooleanField(default=True, verbose_name='حفظ في الملفات')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paused', 'متوقف'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='active', max_length=10, verbose_name='الحالة')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل التالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='قالب التقرير')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقرير مجدول',
                'verbose_name_plural': 'التقارير المجدولة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('running', 'قيد التشغيل'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='queued', max_length=10, verbose_name='الحالة')),
                ('parameters', models.JSONField(default=dict, verbose_name='المعاملات')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='ملف المخرجات')),
                ('output_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='تنسيق المخرجات')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('record_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد السجلات')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='المجموع الإجمالي')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='قالب التقرير')),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.scheduledreport', verbose_name='التقرير المجدول')),
            ],
            options={
                'verbose_name': 'تنفيذ تقرير',
                'verbose_name_plural': 'تنفيذات التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('monthly_income', 'الدخل الشهري'), ('monthly_expenses', 'المصروفات الشهرية'), ('savings_rate', 'معدل الادخار'), ('expense_by_category', 'المصروفات حسب التصنيف'), ('income_vs_expense', 'الدخل مقابل المصروفات'), ('budget_performance', 'أداء الميزانية'), ('account_balance', 'رصيد الحساب'), ('debt_ratio', 'نسبة الدين'), ('investment_return', 'عائد الاستثمار')], max_length=30, verbose_name='نوع المقياس')),
                ('period_start', models.DateField(verbose_name='تاريخ بداية الفترة')),
                ('period_end', models.DateField(verbose_name='تاريخ نهاية الفترة')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='القيمة')),
                ('breakdown_data', models.JSONField(default=dict, verbose_name='بيانات التفصيل')),
                ('chart_data', models.JSONField(default=dict, verbose_name='بيانات الرسم البياني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليل مالي',
                'verbose_name_plural': 'التحليلات المالية',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'metric_type', 'period_start', 'period_end')},
            },
        ),
    ]
