# Generated by Django 5.2.2 on 2025-09-29 04:25

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم التصنيف الأب')),
                ('category_type', models.CharField(choices=[('income', 'دخل'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=10, verbose_name='نوع التصنيف')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='لون التصنيف')),
                ('icon', models.CharField(default='fas fa-folder', max_length=100, verbose_name='أيقونة التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='حد الميزانية الشهرية')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومي')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
            ],
            options={
                'verbose_name': 'قالب تصنيف',
                'verbose_name_plural': 'قوالب التصنيفات',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('name', 'parent_name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('category_type', models.CharField(choices=[('income', 'دخل'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=10, verbose_name='نوع التصنيف')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='لون التصنيف')),
                ('icon', models.CharField(default='fas fa-folder', max_length=100, verbose_name='أيقونة التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='حد الميزانية الشهرية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='التصنيف الأب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
