# Generated by Django 5.2.2 on 2025-09-29 04:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربعي'), ('yearly', 'سنوي'), ('custom', 'مخصص')], max_length=10, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فترة ميزانية',
                'verbose_name_plural': 'فترات الميزانيات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الميزانية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مجموع الميزانية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=10, verbose_name='الحالة')),
                ('alert_threshold', models.CharField(choices=[('none', 'لا توجد تنبيهات'), ('80_percent', 'عند الوصول لـ 80%'), ('90_percent', 'عند الوصول لـ 90%'), ('100_percent', 'عند الوصول لـ 100%'), ('custom', 'مخصص')], default='90_percent', max_length=15, verbose_name='عتبة التنبيه')),
                ('custom_alert_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة التنبيه المخصصة')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المجموع المنفق')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع الدخل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المخصص')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المنفق')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='الميزانية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف ميزانية',
                'verbose_name_plural': 'تصنيفات الميزانية',
                'unique_together': {('budget', 'category')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('budget_threshold', 'تجاوز عتبة الميزانية'), ('category_threshold', 'تجاوز عتبة التصنيف'), ('low_funds', 'نفاد الأموال'), ('achievement', 'إنجاز هدف')], max_length=20, verbose_name='نوع التنبيه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('message', models.TextField(verbose_name='رسالة التنبيه')),
                ('status', models.CharField(choices=[('unread', 'غير مقروء'), ('read', 'مقروء'), ('acknowledged', 'معترف به')], default='unread', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget', verbose_name='الميزانية')),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetcategory', verbose_name='تصنيف الميزانية')),
            ],
            options={
                'verbose_name': 'تنبيه ميزانية',
                'verbose_name_plural': 'تنبيهات الميزانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(through='budgets.BudgetCategory', to='categories.category', verbose_name='التصنيفات'),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetperiod', verbose_name='فترة الميزانية'),
        ),
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('categories_data', models.JSONField(verbose_name='بيانات التصنيفات')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مجموع الميزانية')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربعي'), ('yearly', 'سنوي'), ('custom', 'مخصص')], default='monthly', max_length=10, verbose_name='نوع الفترة')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومي')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب ميزانية',
                'verbose_name_plural': 'قوالب الميزانيات',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
